# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Woo's Blog
subtitle: Just Do & Write it !
description:
author: Jim Woo
language: zh-Hans
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://inwoo.me
root: /
permalink: :category/:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
  Joke: joke
  Tech: hack
  Internet: net
tag_map:
  JavaScript: js
  Css: css
  NodeJS: node

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next 


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
- type: git
  repo: git@github.com:zqjimlove/zqjimlove.github.io.git
  branch: master
  message: Site updated:{{ now('YYYY-MM-DD HH:mm:ss') }})
- type: git
  repo: git@e.coding.net:jimwoo/blog.git
  branch: coding-pages
  message: Site updated:{{ now('YYYY-MM-DD HH:mm:ss') }})

# # Search
# search:
#   path: search.xml
#   field: post
#   format: html
#   limit: 10000

# Custom
avatar: /uploads/avatar.jpg
google_analytics: UA-39715938-1


cdn:
  enable: false
  base: //i.inwoo.me/
  excludeTags:
    - link
    - script


css_minifier:
  enable: false

js_minifier:
  enable: false

image_minifier:
  enable: false

algolia:
  applicationID: 'O53TIH124Y'
  apiKey: '8ed06f70ea649e0bf006a20053097d7e'
  indexName: 'blog'
  chunkSize: 5000