name: Blog CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: hexo
      - name: Checkout submodules
        shell: bash
        run: |
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Use Node.js 10.x # 配置Node环境
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Setup ENV
        env:
          ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-keyscan e.coding.net >> ~/.ssh/known_hosts
          git config --global user.name 'github@zqjimlove'
          git config --global user.email 'zqjimlove@gmail.com'
      - name: Setup Hexo
        run: |
          npm i -g hexo-cli
          npm i
      - name: Deploy
        evn:
          HEXO_ALGOLIA_INDEXING_KEY: ${{secrets.HEXO_ALGOLIA_INDEXING_KEY}}
        run: |
          hexo clean
          hexo g --config _config.yml,_config.production.yml -d
          echo $HEXO_ALGOLIA_INDEXING_KEY
          hexo algolia
